CPU_WARNING = 70
CPU_CRITICAL = 90

MEMORY_WARNING = 75
MEMORY_CRITICAL = 90

DISK_WARNING = 80
DISK_CRITICAL = 95

MONITOR_INTERVAL = 3
# Thread thresholds
HIGH_THREAD_COUNT_THRESHOLD = 100

MONITOR_INTERVAL_SECONDS = MONITOR_INTERVAL

# Network thresholds
NETWORK_WARNING_THRESHOLD = 500
NETWORK_CRITICAL_THRESHOLD = 1000
# File descriptor thresholds
FD_WARNING_THRESHOLD = 500
FD_CRITICAL_THRESHOLD = 900
