"""
analyzer.py

Coordinates all diagnostic rules and returns the findings
generated by those rules.
"""

from backend.diagnostics.rules import ALL_RULES


def run_diagnostics(
    recent_history: list[dict],
    processes: list[dict],
) -> list[dict]:
    """
    Run all registered diagnostic rules.

    Each rule returns:
        - a diagnostic dictionary if a problem is detected
        - None if the rule condition is not met

    The analyzer collects only the detected diagnostics.
    """

    diagnostics = []

    for rule in ALL_RULES:
        result = rule(recent_history, processes)

        if result is not None:
            diagnostics.append(result)

    return diagnostics

